GET  http://localhost:3000/api/auth/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjMyOTg5YzkyY2FiMTQ4YTBhMzE1ODg3IiwiaWF0IjoxNjYzNjY2ODk1fQ.aNcT83qs2IObTDu5BVz3rh69hileU2Tov90eOApbs_U

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username" : "test122",
    "password" : "test12",
    "comfirmPassword" : "test12"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/x-www-form-urlencoded

{
    "username" : "test122",
    "password" : "test12",
}
###

PUT http://localhost:3000/api/auth/setting
content-type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjMwZDgyNzRjNzdmNjllNDRmMmFkMTE5IiwiaWF0IjoxNjYyOTc3NjI2fQ.d8I4YeulQ_4X7OkgCbifbktJaN7IAd8RDKpuZHeoA6c

{
    
}

###

GET http://localhost:3000/api/blog
content-type: application/json
###

POST  http://localhost:3000/api/blog/newblog
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjMwZDgyNzRjNzdmNjllNDRmMmFkMTE5IiwiaWF0IjoxNjYyOTc3NjI2fQ.d8I4YeulQ_4X7OkgCbifbktJaN7IAd8RDKpuZHeoA6c

{
    "title" : "bai viet dau tien",
    "body" : " co gai ay that dep",
}

###
PUT  http://localhost:3000/api/blog/63371a589d37beedd0e28296
content-type: application/json
Content-Disposition: form-data; name="image",filenane="male-user.jpg";
content-type: image/jpeg
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoiNjMzNzE5ZDY5ZDM3YmVlZGQwZTI4MjkzIiwiaWF0IjoxNjY0NTU1NTA1fQ.uWVbW5UMnGi4PCBHNY6dEmwOoMM6MZJfKEOslN1x0rQ

{
    "title" : "bai viet dau tien",
    "body" : " co gai ay that dep",
}

<D:/dowloads/male-user.jpg>